### ISSUE TITLE
Version 1.2.2

### ISSUE THREAD

**Issue by SmallLars** [SmallLars/openssl-ccm#5]
@jooeycheng @franee

My current system is using lower case letters to =o

Any reasons why I should not publish the current master as version 1.2.2?

**Comment by jooeycheng** [comment]
hey @SmallLars, I'm not understanding the question. It seems that current master is already published as v1.2.1. (perhaps i missed something?)

What changes would v1.2.2 bring?

**Comment by SmallLars** [comment]
I am using Manjaro Linux.
`ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`
`OpenSSL 1.1.1  11 Sep 2018.`

> I thought v1.2.1 was the latest, with the lowercase cipher fix bcos it shows as released on 6 Jan 2019 on GitHub.
Yes, I added the missing tags, sorry. Sad that GitHub do not use the date of the commits the tags pointing to.
